@RiskService_HostAddress = http://localhost:5034


GET {{RiskService_HostAddress}}/risk/positions

###

GET {{RiskService_HostAddress}}/risk/portfolios

###

POST {{RiskService_HostAddress}}/risk/snapshot
